apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nginx-front.fullname" . }}-config
data:
{{- range $path, $config := .Values.nginxConfig }}
  {{ $path }}: |
{{ tpl $config $ | indent 4 -}}
{{- end -}}